version: '3.8'

services:
  frontend-main:
    build:
      context: ./frontend-tugas-akhir
      target: prod
    ports:
      - "3000:3000"
    env_file:
      - ./frontend-tugas-akhir/.env
    depends_on:
      - backend-main
    restart: unless-stopped

  frontend-admin:
    build:
      context: ./admin-tugas-akhir
      target: prod
    ports:
      - "3001:3000"
    env_file:
      - ./admin-tugas-akhir/.env
    depends_on:
      - backend-main
    restart: unless-stopped

  backend-main:
    build:
      context: ./backend-tugas-akhir
      target: prod
    ports:
      - "4000:4000"
    env_file:
      - ./backend-tugas-akhir/.env
    volumes:
      - ./backend-tugas-akhir/uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  backend-worker:
    build:
      context: ./backend-2-tugas-akhir
      target: prod
    ports:
      - "8000:8000"
    env_file:
      - ./backend-2-tugas-akhir/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    ports:
      - "127.0.0.1:54321:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/scripts:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB && (pg_isready -U $POSTGRES_USER -d $POSTGRES_DB_WORKER)"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      bash -c "docker-entrypoint.sh postgres & 
      sleep 10 && 
      PGUSER=$POSTGRES_USER PGPASSWORD=$POSTGRES_PASSWORD /scripts/database.sh &&
      wait"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend-main
      - frontend-admin
      - backend-main
      - backend-worker
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
